version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-setup:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install Yarn package manager
                command: curl -o- -L https://yarnpkg.com/install.sh | bash
            - run:
                name: Install javascript dependencies (using Yarn)
                command: yarn install --ignore-engines
  build-web:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Build design tokens for web
                command: yarn web
workflows:
  build-deploy:
    jobs:
      - build-setup
      - build-web
